### ISSUE TITLE
Pixi environments failing to activate

### ISSUE THREAD

**Issue by giuthas** [pavelzw/pixi-pycharm#43] opened 2024-10-12 05:11 UTC
## Description

I had a working setup with pixi.toml, but as I moved to pyproject.toml (and deleted the whole of .pixi when doing so) I've ended up with pixi environments not activating in pycharm for some reason even though they are there to be chosen.

I do also have some regular conda environments that I've not yet dismantled and one of them was active while trying to get things to run.

## Versions

```bash
❯ pixi --version
pixi 0.32.1
❯ pixi list | grep pixi-pycharm
pixi-pycharm                          0.0.7         unix_1234567_0       8.6 KiB    conda  pixi-pycharm-0.0.7-unix_1234567_0.conda
```

PyCharm version: 0.0.7 (see *About PyCharm*)

Platform: Linux-64 / Pop!_OS 22.04 LTS

## Logs

```
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['run', '-n', 'default', '--no-capture-output', 'python', '-c', 'import sys; print(sys.executable)']
Attempting to run: ['list', '-n', 'default']
Attempting to run: ['list', '-n', 'default']
Attempting to run: ['list', '-n', 'default']
Attempting to run: ['list', '-n', 'default']
Attempting to run: ['list', '-n', 'default']
Attempting to run: ['list', '-n', 'default']
Attempting to run: ['list', '-n', 'default']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['run', '-n', 'devel', '--no-capture-output', 'python', '-c', 'import sys; print(sys.executable)']
Attempting to run: ['list', '-n', 'devel']
Attempting to run: ['list', '-n', 'devel']
Attempting to run: ['list', '-n', 'devel']
Attempting to run: ['list', '-n', 'devel']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['run', '-n', 'devel', '--no-capture-output', 'python', '-c', 'import sys; print(sys.executable)']
Traceback (most recent call last):
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 178, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 156, in main
    conda_run(args)
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 120, in conda_run
    os.execlp(
  File "<frozen os>", line 592, in execlp
  File "<frozen os>", line 609, in execvp
  File "<frozen os>", line 651, in _execvpe
  File "<frozen os>", line 642, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['run', '-n', 'devel', '--no-capture-output', 'python', '-c', 'import sys; print(sys.executable)']
Traceback (most recent call last):
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 178, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 156, in main
    conda_run(args)
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 120, in conda_run
    os.execlp(
  File "<frozen os>", line 592, in execlp
  File "<frozen os>", line 609, in execvp
  File "<frozen os>", line 651, in _execvpe
  File "<frozen os>", line 642, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['run', '-n', 'default', '--no-capture-output', 'python', '-c', 'import sys; print(sys.executable)']
Traceback (most recent call last):
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 178, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 156, in main
    conda_run(args)
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 120, in conda_run
    os.execlp(
  File "<frozen os>", line 592, in execlp
  File "<frozen os>", line 609, in execvp
  File "<frozen os>", line 651, in _execvpe
  File "<frozen os>", line 642, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['run', '-n', 'devel', '--no-capture-output', 'python', '-c', 'import sys; print(sys.executable)']
Traceback (most recent call last):
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 178, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 156, in main
    conda_run(args)
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 120, in conda_run
    os.execlp(
  File "<frozen os>", line 592, in execlp
  File "<frozen os>", line 609, in execvp
  File "<frozen os>", line 651, in _execvpe
  File "<frozen os>", line 642, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['run', '-n', 'default', '--no-capture-output', 'python', '-c', 'import sys; print(sys.executable)']
Traceback (most recent call last):
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 178, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 156, in main
    conda_run(args)
  File "/home/jpalo/tyot/source/cast/.pixi/envs/devel/libexec/conda", line 120, in conda_run
    os.execlp(
  File "<frozen os>", line 592, in execlp
  File "<frozen os>", line 609, in execvp
  File "<frozen os>", line 651, in _execvpe
  File "<frozen os>", line 642, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['run', '-n', 'default', '--no-capture-output', 'python', '-c', 'import sys; print(sys.executable)']
Traceback (most recent call last):
  File "/home/jpalo/tyot/source/cast/.pixi/envs/default/libexec/conda", line 178, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/home/jpalo/tyot/source/cast/.pixi/envs/default/libexec/conda", line 156, in main
    conda_run(args)
  File "/home/jpalo/tyot/source/cast/.pixi/envs/default/libexec/conda", line 120, in conda_run
    os.execlp(
  File "<frozen os>", line 592, in execlp
  File "<frozen os>", line 609, in execvp
  File "<frozen os>", line 651, in _execvpe
  File "<frozen os>", line 642, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by pavelzw** [comment] 2024-10-12 06:43
Do you have a reproducer that I could try to follow?

**Comment by pavelzw** [comment] 2024-11-15 17:40
closing for now since there was no reaction
if you still have this issue with 0.0.8, feel free to ping me again with a reproducer

**Closed by pavelzw** 2024-11-15 17:40 UTC
